<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="LAPTOP-9DSQ4N61" ignored="0" name="Test" tests="5" failures="1" timestamp="2022-02-05T09:59:45 IST" time="0.12" errors="0">
  <testcase name="login1" time="0.017" classname="com.testng.features.Test_Demo"/>
  <testcase name="login2" time="0.003" classname="com.testng.features.Test_Demo">
    <skipped/>
  </testcase> <!-- login2 -->
  <testcase name="login2" time="0.002" classname="com.testng.features.Test_Demo">
    <skipped/>
  </testcase> <!-- login2 -->
  <testcase name="login2" time="0.002" classname="com.testng.features.Test_Demo">
    <skipped/>
  </testcase> <!-- login2 -->
  <testcase name="login2" time="0.002" classname="com.testng.features.Test_Demo">
    <failure type="java.lang.AssertionError" message="expected [we345] but found [vn532]">
      <![CDATA[java.lang.AssertionError: expected [we345] but found [vn532]
at com.testng.features.Test_Demo.login2(Test_Demo.java:25)
at java.util.ArrayList.forEach(Unknown Source)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- login2 -->
</testsuite> <!-- Test -->
